name: orzu_grand
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
 
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

  fonts:
     - family: Open Sans
       fonts:
         - asset: assets/fonts/open_seans/OpenSans-Bold.ttf
           weight: 600
         - asset: assets/fonts/open_seans/OpenSans-ExtraBold.ttf
           weight: 800
         - asset: assets/fonts/open_seans/OpenSans-SemiBold.ttf
           weight: 700

